# This is a basic workflow that is manually triggered

name: Create Redirect

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      id:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Redirect Name'
        # Default value if no value is explicitly provided
        default: 'id'
        # Input has to be provided for the workflow to run
        required: true
      url:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Redirect URL'
        # Default value if no value is explicitly provided
        default: 'https://'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir ${{ github.event.inputs.id }}
          cd ${{ github.event.inputs.id }}
          echo "<title>Redirecting...</title>" > index.html
          echo "<meta http-equiv=\"refresh\" content=\"0; url='${{ github.event.inputs.url }}'\" />" >> index.html
          date > date.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
